config/routes.rb
Rails.application.routes.draw do


  get 'my_page/index'

  # shorten the admin pages url to /admin
  get 'admin' => 'admin#index'


  get 'comment/index'
  # change the session actions url to /login and /logout
  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :hours, :courses, :users, :news_feeds
  resources :comments do
    resources :comments
  end

  resources :news_feeds do
    resources :comments
  end

  get 'news_feeds/index'

  root 'news_feeds#index'

end

app/models/hour.rb
class Hour < ApplicationRecord
  belongs_to :user
  belongs_to :course

  validates :user, :course, presence: true
  validates :hours, presence: true, numericality: {greater_than: 0}
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  before_action :set_hour, only: [:show, :edit, :update, :destroy]


  # GET /hours associated to the current user
  def index
    @hours = Hour.where(user: @current_user)
    get_total
  end

  # GET /hours/1
  # GET /hours/1.json
  def show
  end

  # GET /hours/new
  def new
    @hour = Hour.new

    respond_to do |format|
      format.js
    end
  end

  # GET /hours/1/edit
  def edit
  end


  # POST /hours
  # POST /hours.json
  def create
    @hour = Hour.new(hour_params)
    @hour.user = @current_user

    respond_to do |format|
      if @hour.save
        format.html { redirect_to hours_url}
        format.json { render :show, status: :created, location: @hour }
      else
        format.html { render :new }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hours/1
  # PATCH/PUT /hours/1.json
  def update
    respond_to do |format|
      if @hour.update(hour_params)
        format.html { redirect_to hours_url}
        format.json { render :show, status: :ok, location: @hour }
      else
        format.html { render :edit }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours/1
  # DELETE /hours/1.json
  def destroy
    @hour.destroy
    respond_to do |format|
      format.html { redirect_to hours_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hour
      @hour = Hour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hour_params
      params.require(:hour).permit(:user_id, :course_id, :date, :hours)
    end

  # Sum up the total amount of hours
  def get_total
    @total = 0
    @hours.each do |h|
      @total += h.hours
    end
    return @total
  end
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/views/hours/_form.html.erb
<%= form_for(hour) do |f| %>
    <% if hour.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(hour.errors.count, "error") %> prohibited this hour from being saved:</h2>

          <ul>
            <% hour.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div id="hoursFormContainter">
      <div class="field" id="fieldCourse">
        <%  @courses = Course.all %>
        <%= f.collection_select :course_id, @courses, :id, :name %>
      </div>

      <div class="field" id="fieldDate">
        <%= f.label :date %>
        <%= f.date_select :date %>
      </div>


      <div class="field" id="fieldHours">
        <%= f.label :hours %>
        <%= f.text_field :hours%>
      </div>

      <div class="actions" id="createHourButton">
        <%= f.submit %>
      </div>
    </br>
<% end %>
</div>

app/views/hours/edit.html.erb
<h1>Edit</h1>

<%= render 'form', hour: @hour %>

<%= link_to 'Back', hours_path %>

app/views/hours/index.html.erb
<h1>Timesheet</h1>

<div class="container">
  <div class="row col-md-6 col-md-offset-2 custyle">
    <table class="table table-striped custab" id="hoursTable">
      <thead>

      <tr>
        <th>Subject</th>
        <th>Date</th>
        <th>Hours</th>
        <th class="text-center">Action</th>
      </tr>
      </thead>
      <tr>
        <% @hours.each do |hour| %>
        <td><%= hour.course.name %></td>
        <td><%= hour.date %></td>
        <td><%= hour.hours %></td>
            <td class="text-center">
              <%= link_to 'Edit', edit_hour_path(hour), class:'btn btn-info btn-xs'%> <a></a><%= link_to 'Delete', hour, method: :delete, class:'btn btn-info btn-xs', data: {confirm: 'Are you sure?'} %></a></td>
            </tr>
        <% end %>
    </table>
  </div>
</div>
<br>
<%= link_to 'Log Hours', new_hour_path, id: 'showHourForm', class:"btn btn-primary btn-default", remote: true %>
<div id="newHourFormContainer">
  <!-- the new form will be rendered here -->
</div>

app/views/hours/new.html.erb
<h1>Timesheet</h1>

<%= render 'form', hour: @hour %>

<%= link_to 'Back', hours_path %>

app/views/hours/new.js.erb
$('#newHourFormContainer').html("<%=j render(partial: 'form', locals:{hour: @hour})%>");

app/views/hours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @hour.user %>
</p>

<p>
  <strong>Course:</strong>
  <%= @hour.course %>
</p>

<p>
  <strong>Date:</strong>
  <%= @hour.date %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @hour.hours %>
</p>

<%= link_to 'Edit', edit_hour_path(@hour) %> |
<%= link_to 'Back', hours_path %>