config/routes.rb
Rails.application.routes.draw do


  get 'my_page/index'

  # shorten the admin pages url to /admin
  get 'admin' => 'admin#index'


  get 'comment/index'
  # change the session actions url to /login and /logout
  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :hours, :courses, :users, :news_feeds
  resources :comments do
    resources :comments
  end

  resources :news_feeds do
    resources :comments
  end

  get 'news_feeds/index'

  root 'news_feeds#index'

end

app/models/news_feed.rb
class NewsFeed < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :text, presence: true, length: 1..1000
  validates :title, length: 1..100
  validates :user, presence: true
end

app/controllers/news_feeds_controller.rb
class NewsFeedsController < ApplicationController
  before_action :set_news_feed, only: [:show, :edit, :update, :destroy]
  before_action :is_authorized?, only: [:edit, :update, :destroy]

  # GET /news_feeds
  # GET /news_feeds.json
  def index
    @news_feeds = NewsFeed.all
  end

  # GET /news_feeds/1
  # GET /news_feeds/1.json
  def show
    @comments = Comment.where(news_feed_id: @news_feed.id).order("created_at DESC")
  end

  # GET /news_feeds/new
  def new
    @news_feed = current_user.news_feeds.build
    respond_to do |format|
      format.js
    end
  end

  # GET /news_feeds/1/edit
  def edit
  end


  # POST /news_feeds
  # POST /news_feeds.json
  def create
    @news_feed = current_user.news_feeds.build(news_feed_params)

    respond_to do |format|
      if @news_feed.save
        format.html { redirect_to news_feeds_path}
        format.json { render :show, status: :created, location: @news_feed }
      else
        format.html { render :new }
        format.json { render json: @news_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_feeds/1
  # PATCH/PUT /news_feeds/1.json
  def update
    respond_to do |format|
      if @news_feed.update(news_feed_params)
        format.html { redirect_to @news_feed}
        format.json { render :show, status: :ok, location: @news_feed }
      else
        format.html { render :edit }
        format.json { render json: @news_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_feeds/1
  # DELETE /news_feeds/1.json
  def destroy
    @news_feed.destroy
    respond_to do |format|
      format.html { redirect_to news_feeds_url }
      format.json { head :no_content }
    end
  end

  private
  def is_authorized?
    if current_user.id!=@news_feed.user_id&&!current_user.admin
      redirect_to news_feeds_path, notice: "Not authorized" and return
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_news_feed
    @news_feed = NewsFeed.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def news_feed_params
    params.require(:news_feed).permit(:title, :text, :user_id)
  end
end

app/helpers/news_feeds_helper.rb
module NewsFeedsHelper
end

app/views/news_feeds/_form.html.erb
<div id="formContainer">
  <%= form_for(news_feed) do |f| %>
      <% if news_feed.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(news_feed.errors.count, "error") %> prohibited this news_feed from being saved:</h2>
            <ul>
              <% news_feed.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>


      <div class="actions">
      </div>

      <section>
        <div class="form-group_new" id="newsTitle">
          <%= f.label :Title %>
          <%= f.text_field :title, class: "form-control", :size => "75" %>
        </div>

        <div class="form-group_new" id="newsText">
          <label for=exampleInputName2"><%= f.label :content %></label>
          <%= f.text_area :text, class: "form-control", :rows => 10%>
        </div>
        <%= f.submit "Publish post", class: "btn btn-default" %>


  <% end %>

  </section>
</div>

app/views/news_feeds/edit.html.erb
<h1 id="editNewsHeader">Endre innlegg</h1>

<%= render 'form', news_feed: @news_feed %>

<%= link_to 'Show', @news_feed %> |
<%= link_to 'Back', news_feeds_path %>

app/views/news_feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="header">News</h1>

<%= link_to 'New post', new_news_feed_path, class:"btn btn-primary btn-default", id: "showNewsFormBtn", remote: true %>

<div id="newNewsFormContainer">
  <!-- the new news form is rendered here -->
</div>

<table>
  <thead>
  </thead>

  <tbody>
  <% @news_feeds.each do |news_feed| %>

      <div class="container">

        <div class="col-md-11 blogShort">

          <br><p>
            <h2 class="newsFeedTitle"><%= link_to news_feed.title, news_feed %></h2>
            <p><%= news_feed.text %></p>
            <p>By: <%= news_feed.user.name %></p>
            </p>
            <p>
            <% if current_user.id == news_feed.user_id||current_user.admin %>
                <li class="linkList"><%= link_to 'Edit', edit_news_feed_path(news_feed) %></li>
                <li class="linkList"><%= link_to 'Delete', news_feed, method: :delete, data: {confirm: 'Are you sure?'} %></li>
            <% end %>
            </p>
          </article>
          </br>
        </div>
      </div>
      </div>


  <% end %>
  </tbody>

</table>

app/views/news_feeds/new.html.erb
<h1  id="editNewsHeader">News</h1>

<%= render 'form', news_feed: @news_feed %>

<%= link_to 'Back', news_feeds_path %>

app/views/news_feeds/new.js.erb
$('#newNewsFormContainer').html("<%=j render(partial: 'form', locals:{ news_feed: @news_feed})%>");

app/views/news_feeds/show.html.erb
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.2/css/bootstrapValidator.min.css"/>
<table>
  <thead>
  </thead>
  <tbody>
  <div class="container">
    <div class="col-md-11 blogShort">
      <article></article>
      <p id="notice"><%= notice %></p>
      <article><p>
        <h2 class="newsFeedTitle"><%= @news_feed.title %></h2>
        <p><%= @news_feed.text %></p>
        <p>By: <%= @news_feed.user.name %></p>
        </p>
      </article>
    </div>
  </div>
  </tbody>
</table>

<%= link_to 'Show/Hide Comments', '#', id: "comments-link"%>
<div id="commentContainer">
  <%= render partial: 'comments/comment'%>
</div>