config/routes.rb
Rails.application.routes.draw do


  get 'my_page/index'

  # shorten the admin pages url to /admin
  get 'admin' => 'admin#index'


  get 'comment/index'
  # change the session actions url to /login and /logout
  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :hours, :courses, :users, :news_feeds
  resources :comments do
    resources :comments
  end

  resources :news_feeds do
    resources :comments
  end

  get 'news_feeds/index'

  root 'news_feeds#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TIMESHEET-JMJ-EXAM</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="navBarTop">
  <% if is_logged_in? %>
      <%= link_to "Home", news_feeds_path %>
      <%= link_to "Timesheet", hours_path %>
      <%= link_to "My page", my_page_index_path %>
      <% if current_user.admin %>
          <%= link_to "Admin", admin_path, method: :get %>
      <% end %>
      <%= link_to "Log out", logout_path, method: :delete %>
      <div id="userLoggedIn">
        Logged in as:  <%= current_user.name %>
      </div>
  <% end %>
</div>
<%= yield %>
<footer>
  <p>Joakim Söderstrand, Mathias Svendsen, Jens Svendsen Thorbjørnsen<a style="color:#ffffff; text-decoration:none;"> ©
    2017 - <a href="https://bitbucket.org/josoder/ruby_assignment">BitBucket</a></a></p>
</footer>
</body>
</html>